name: Build and Test

on:
  push:
    branches:
      - master
      - main
      - ci
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-22.04]
        java: [8, 17]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Dependencies
        run: |
          git clone --recursive https://github.com/martinpaljak/oracle_javacard_sdks.git $HOME/javacard-sdk
          cd $HOME/javacard-sdk
          git checkout -b last e305a1a

      - name: "Set environmental variables"
        run: |
          echo "JC_CLASSIC_HOME=$HOME/javacard-sdk/jc305u4_kit" >> $GITHUB_ENV

      - name: Build
        run: |
          mvn initialize
          mvn package

